name: probs
env:
  name: togyzkumalak
  n_max_episode_steps: 200
cmd: train
infra:
  log: mem
  device: cpu
  sub_processes_cnt: 4
  self_play_threads: 2
  mem_max_episodes: 500
train:
  n_high_level_iterations: 20
  v_train_episodes: 5
  q_train_episodes: 5
  q_dataset_episodes_sub_iter: 1
  dataset_drop_ratio: 0
  checkpoints_dir: C:/Users/Admin/Documents/Toguzkumalak/gym-togyzkumalak-master/togyzkumalak-engine/models/probs/checkpoints
  train_batch_size: 32
  self_learning_batch_size: 32
  get_q_dataset_batch_size: 32
  num_q_s_a_calls: 10
  max_depth: 8
  alphazero_move_num_sampling_moves: 3
  q_add_hardest_nodes_per_step: 0
evaluate:
  evaluate_n_games: 5
  randomize_n_turns: 2
  enemy:
    kind: random
model:
  value:
    class: ValueModelTK_v1
    learning_rate: 0.001
    weight_decay: 0.0001
  self_learner:
    class: SelfLearningModelTK_v1
    learning_rate: 0.001
    weight_decay: 0.0001
enemy:
  kind: random
